---
 - hosts: localhost
   remote_user: test
   tasks:
     - name: get docker version
       shell: "docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1"
       register: version

     - name: docker image list
       shell: "echo docker images"
      
     - name: docker env set
       shell: "eval $(minikube docker-env)"


     - name: docker build image
       shell: "docker build -f Dockerfile -t python-docker:v1 ."

     - name: Kubernetes Deployment
       shell: "kubectl apply -f deployment.yaml"

     - debug: var=version.stdout

     - name: do something if version is 1.13.0
       shell: "echo it is 1.13.0"
       when: version.stdout == "1.13.0"

     - name: do nothing if version is 1.13.0
       shell: "echo nothing"
       when: version.stdout != "1.13.0"