apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  selector:
    app: python-docker
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  selector:
    matchLabels:
      app: python-flask
  replicas: 4
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: python-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000